language: node_js

node_js : 
    - "0.10"
    - "0.11"

addons:
    postgresql: "9.3"

before_script:
  - psql -f test/lib/create-db.sql -U postgres
  - psql -f test/lib/create-tables.sql -U postgres